name:                bricktrader
version:             0.1.0.0
github:              "githubuser/bricktrader"
license:             AGPL-3
author:              "Tama Waddell"
copyright:           "2022 Tama Waddell"
description:         Please see the README on GitHub at <https://github.com/tamaw/bricktrader#readme>

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- DeriveGeneric
- OverloadedStrings
- LambdaCase
- DeriveAnyClass
- TemplateHaskell

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- containers
- brick
- vty
- vector
- time
- lens
- http-client
- http-types
- wreq
- aeson
- lens-aeson
- aeson-casing
- unix
- http-client-tls
- record-dot-preprocessor
- record-hasfield
- SHA
- clock

ghc-options:
- -F -pgmF record-dot-preprocessor
- -Wall
- -Wcompat
- -Widentities
# - -Wincomplete-record-updates
# - -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  bricktrader-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -split-sections
    dependencies:
    - bricktrader

tests:
  bricktrader-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bricktrader
